### ISSUE TITLE
貌似有些问题（？）

### ISSUE THREAD

**Issue by CraftKevin** [XiaoLin0815/QQ2TG#5]
按照readme操作之后，在telegram中发送/new_chat回复一个空的好友列表
希望能说明一下env中参数的作用
![img7944](https://user-images.githubusercontent.com/20182292/46523098-465efa00-c8b7-11e8-835c-a703a1bdf6f6.PNG)

**Comment by LynMoe** [comment]
@CraftKevin 可能是这样的，因为我不常用这个功能，也没做分页，所以可能会爆炸。等有时间的时候看看写个分页

**Comment by CraftKevin** [comment]
coolq-http-api配置:
<img width="285" alt="2018-10-05 3 59 24" src="https://user-images.githubusercontent.com/20182292/46523331-f92f5800-c8b7-11e8-8347-52180e784a63.png">

**Comment by CraftKevin** [comment]
（哇秒回
（好的

**Comment by CraftKevin** [comment]
感觉是我coolqapi配置的问题，网页端也获取不到信息

**Comment by LynMoe** [comment]
@CraftKevin github bot (hhh

**Comment by CraftKevin** [comment]
<img width="279" alt="2018-10-05 4 08 02" src="https://user-images.githubusercontent.com/20182292/46523631-e9644380-c8b8-11e8-9d0c-89b039dd0a12.png">
是这样🐎

**Comment by CraftKevin** [comment]
(我这么填的）

**Comment by LynMoe** [comment]
![image](https://user-images.githubusercontent.com/20554060/46523753-4eb83480-c8b9-11e8-8839-004c38076859.png)
是这样的

chat_id 就是你的id


send_to 就是私聊消息要发送到的id，一般来说和chat_id一样即可，我是发送到小本本里所以和chat_id不一样


group里左边一列是qq群号，右边一列是telegram chat id

**Comment by CraftKevin** [comment]
原来如此（

**Comment by CraftKevin** [comment]
[WARNING]
[Msg]file_get_contents(http://0.0.0.0:5700/get_login_info): failed to open stream: Connection refused
[File]"\/data\/root\/QQ2TG\/core\/Server.php"
[Line]27
[Context]{"int":0}
![huaji.webp](https://wget-1252913589.cos.ap-beijing.myqcloud.com/lhhuaji.png)

**Comment by LynMoe** [comment]
@CraftKevin 你的酷q地址没填对...

**Comment by CraftKevin** [comment]
可是我是这么配置的（
![coolq-http-api](https://user-images.githubusercontent.com/20182292/46523331-f92f5800-c8b7-11e8-8347-52180e784a63.png)

**Comment by CraftKevin** [comment]
位置在这~/coolq-data/app/io.github.richardchien.coolqhttpapi/config.json

**Comment by LynMoe** [comment]
@CraftKevin 那你qq2tg上要填你服务器的ip啊（（

**Comment by CraftKevin** [comment]
填的http://0.0.0.0:5700

**Comment by CraftKevin** [comment]
<img width="177" alt="2018-10-05 8 09 53" src="https://user-images.githubusercontent.com/20182292/46534454-b763d900-c8da-11e8-9ac0-55d6be88087a.png">

**Comment by LynMoe** [comment]
.....
请你先了解一下「IP」的概念在来问吧 （（
这种基础不应该在issue里问的 （
